package com.nnk.upstream.dao;

import com.nnk.upstream.vo.InterfaceConfig;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;

public interface InterfaceConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interfaceConfig
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interfaceConfig
     *
     * @mbggenerated
     */
    int insert(InterfaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interfaceConfig
     *
     * @mbggenerated
     */
    int insertSelective(InterfaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interfaceConfig
     *
     * @mbggenerated
     */
    InterfaceConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interfaceConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InterfaceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interfaceConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InterfaceConfig record);


    List<InterfaceConfig> findAll();

    List<InterfaceConfig> findAllpage(HashMap<String, Long> offsetLimit);

    List<InterfaceConfig> find(@Param("merchantno") String merchantno, @Param("interfacename") String interfacename);

    Long count();
}