package com.nnk.upstream.vo;

public class InterfaceConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.merchantNo
     *
     * @mbggenerated
     */
    private String merchantno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.interfaceName
     *
     * @mbggenerated
     */
    private String interfacename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.rechargeType
     *
     * @mbggenerated
     */
    private Byte rechargetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.rechargeUrl
     *
     * @mbggenerated
     */
    private String rechargeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.banlanceUrl
     *
     * @mbggenerated
     */
    private String banlanceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.queryUrl
     *
     * @mbggenerated
     */
    private String queryurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.unrechargeUrl
     *
     * @mbggenerated
     */
    private String unrechargeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.backUrl
     *
     * @mbggenerated
     */
    private String backurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.isExpire
     *
     * @mbggenerated
     */
    private Boolean isexpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.expireTime
     *
     * @mbggenerated
     */
    private Integer expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.encrykey
     *
     * @mbggenerated
     */
    private String encrykey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceConfig.interfaceType
     *
     * @mbggenerated
     */
    private Boolean interfacetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.id
     *
     * @return the value of interfaceConfig.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.id
     *
     * @param id the value for interfaceConfig.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.merchantNo
     *
     * @return the value of interfaceConfig.merchantNo
     *
     * @mbggenerated
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.merchantNo
     *
     * @param merchantno the value for interfaceConfig.merchantNo
     *
     * @mbggenerated
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.interfaceName
     *
     * @return the value of interfaceConfig.interfaceName
     *
     * @mbggenerated
     */
    public String getInterfacename() {
        return interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.interfaceName
     *
     * @param interfacename the value for interfaceConfig.interfaceName
     *
     * @mbggenerated
     */
    public void setInterfacename(String interfacename) {
        this.interfacename = interfacename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.rechargeType
     *
     * @return the value of interfaceConfig.rechargeType
     *
     * @mbggenerated
     */
    public Byte getRechargetype() {
        return rechargetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.rechargeType
     *
     * @param rechargetype the value for interfaceConfig.rechargeType
     *
     * @mbggenerated
     */
    public void setRechargetype(Byte rechargetype) {
        this.rechargetype = rechargetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.rechargeUrl
     *
     * @return the value of interfaceConfig.rechargeUrl
     *
     * @mbggenerated
     */
    public String getRechargeurl() {
        return rechargeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.rechargeUrl
     *
     * @param rechargeurl the value for interfaceConfig.rechargeUrl
     *
     * @mbggenerated
     */
    public void setRechargeurl(String rechargeurl) {
        this.rechargeurl = rechargeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.banlanceUrl
     *
     * @return the value of interfaceConfig.banlanceUrl
     *
     * @mbggenerated
     */
    public String getBanlanceurl() {
        return banlanceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.banlanceUrl
     *
     * @param banlanceurl the value for interfaceConfig.banlanceUrl
     *
     * @mbggenerated
     */
    public void setBanlanceurl(String banlanceurl) {
        this.banlanceurl = banlanceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.queryUrl
     *
     * @return the value of interfaceConfig.queryUrl
     *
     * @mbggenerated
     */
    public String getQueryurl() {
        return queryurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.queryUrl
     *
     * @param queryurl the value for interfaceConfig.queryUrl
     *
     * @mbggenerated
     */
    public void setQueryurl(String queryurl) {
        this.queryurl = queryurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.unrechargeUrl
     *
     * @return the value of interfaceConfig.unrechargeUrl
     *
     * @mbggenerated
     */
    public String getUnrechargeurl() {
        return unrechargeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.unrechargeUrl
     *
     * @param unrechargeurl the value for interfaceConfig.unrechargeUrl
     *
     * @mbggenerated
     */
    public void setUnrechargeurl(String unrechargeurl) {
        this.unrechargeurl = unrechargeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.backUrl
     *
     * @return the value of interfaceConfig.backUrl
     *
     * @mbggenerated
     */
    public String getBackurl() {
        return backurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.backUrl
     *
     * @param backurl the value for interfaceConfig.backUrl
     *
     * @mbggenerated
     */
    public void setBackurl(String backurl) {
        this.backurl = backurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.isExpire
     *
     * @return the value of interfaceConfig.isExpire
     *
     * @mbggenerated
     */
    public Boolean getIsexpire() {
        return isexpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.isExpire
     *
     * @param isexpire the value for interfaceConfig.isExpire
     *
     * @mbggenerated
     */
    public void setIsexpire(Boolean isexpire) {
        this.isexpire = isexpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.expireTime
     *
     * @return the value of interfaceConfig.expireTime
     *
     * @mbggenerated
     */
    public Integer getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.expireTime
     *
     * @param expiretime the value for interfaceConfig.expireTime
     *
     * @mbggenerated
     */
    public void setExpiretime(Integer expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.encrykey
     *
     * @return the value of interfaceConfig.encrykey
     *
     * @mbggenerated
     */
    public String getEncrykey() {
        return encrykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.encrykey
     *
     * @param encrykey the value for interfaceConfig.encrykey
     *
     * @mbggenerated
     */
    public void setEncrykey(String encrykey) {
        this.encrykey = encrykey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceConfig.interfaceType
     *
     * @return the value of interfaceConfig.interfaceType
     *
     * @mbggenerated
     */
    public Boolean getInterfacetype() {
        return interfacetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceConfig.interfaceType
     *
     * @param interfacetype the value for interfaceConfig.interfaceType
     *
     * @mbggenerated
     */
    public void setInterfacetype(Boolean interfacetype) {
        this.interfacetype = interfacetype;
    }

    @Override
    public String toString() {
        return "InterfaceConfig{" +
                "id=" + id +
                ", merchantno='" + merchantno + '\'' +
                ", interfacename='" + interfacename + '\'' +
                ", rechargetype=" + rechargetype +
                ", rechargeurl='" + rechargeurl + '\'' +
                ", banlanceurl='" + banlanceurl + '\'' +
                ", queryurl='" + queryurl + '\'' +
                ", unrechargeurl='" + unrechargeurl + '\'' +
                ", backurl='" + backurl + '\'' +
                ", isexpire=" + isexpire +
                ", expiretime=" + expiretime +
                ", encrykey='" + encrykey + '\'' +
                ", interfacetype=" + interfacetype +
                '}';
    }
}