package com.nnk.upstream.vo;

public class InterfaceRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.merchantNo
     *
     * @mbggenerated
     */
    private String merchantno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.rechargeRequest
     *
     * @mbggenerated
     */
    private String rechargerequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.rechargeResponse
     *
     * @mbggenerated
     */
    private String rechargeresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.queryRequest
     *
     * @mbggenerated
     */
    private String queryrequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.queryResponse
     *
     * @mbggenerated
     */
    private String queryresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.banlanceRequest
     *
     * @mbggenerated
     */
    private String banlancerequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.balanceResponse
     *
     * @mbggenerated
     */
    private String balanceresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.unrechargeRequest
     *
     * @mbggenerated
     */
    private String unrechargerequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.unrechargeResponse
     *
     * @mbggenerated
     */
    private String unrechargeresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.callbackRequest
     *
     * @mbggenerated
     */
    private String callbackrequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interfaceRule.callbackResponse
     *
     * @mbggenerated
     */
    private String callbackresponse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.id
     *
     * @return the value of interfaceRule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.id
     *
     * @param id the value for interfaceRule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.merchantNo
     *
     * @return the value of interfaceRule.merchantNo
     *
     * @mbggenerated
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.merchantNo
     *
     * @param merchantno the value for interfaceRule.merchantNo
     *
     * @mbggenerated
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.rechargeRequest
     *
     * @return the value of interfaceRule.rechargeRequest
     *
     * @mbggenerated
     */
    public String getRechargerequest() {
        return rechargerequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.rechargeRequest
     *
     * @param rechargerequest the value for interfaceRule.rechargeRequest
     *
     * @mbggenerated
     */
    public void setRechargerequest(String rechargerequest) {
        this.rechargerequest = rechargerequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.rechargeResponse
     *
     * @return the value of interfaceRule.rechargeResponse
     *
     * @mbggenerated
     */
    public String getRechargeresponse() {
        return rechargeresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.rechargeResponse
     *
     * @param rechargeresponse the value for interfaceRule.rechargeResponse
     *
     * @mbggenerated
     */
    public void setRechargeresponse(String rechargeresponse) {
        this.rechargeresponse = rechargeresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.queryRequest
     *
     * @return the value of interfaceRule.queryRequest
     *
     * @mbggenerated
     */
    public String getQueryrequest() {
        return queryrequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.queryRequest
     *
     * @param queryrequest the value for interfaceRule.queryRequest
     *
     * @mbggenerated
     */
    public void setQueryrequest(String queryrequest) {
        this.queryrequest = queryrequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.queryResponse
     *
     * @return the value of interfaceRule.queryResponse
     *
     * @mbggenerated
     */
    public String getQueryresponse() {
        return queryresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.queryResponse
     *
     * @param queryresponse the value for interfaceRule.queryResponse
     *
     * @mbggenerated
     */
    public void setQueryresponse(String queryresponse) {
        this.queryresponse = queryresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.banlanceRequest
     *
     * @return the value of interfaceRule.banlanceRequest
     *
     * @mbggenerated
     */
    public String getBanlancerequest() {
        return banlancerequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.banlanceRequest
     *
     * @param banlancerequest the value for interfaceRule.banlanceRequest
     *
     * @mbggenerated
     */
    public void setBanlancerequest(String banlancerequest) {
        this.banlancerequest = banlancerequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.balanceResponse
     *
     * @return the value of interfaceRule.balanceResponse
     *
     * @mbggenerated
     */
    public String getBalanceresponse() {
        return balanceresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.balanceResponse
     *
     * @param balanceresponse the value for interfaceRule.balanceResponse
     *
     * @mbggenerated
     */
    public void setBalanceresponse(String balanceresponse) {
        this.balanceresponse = balanceresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.unrechargeRequest
     *
     * @return the value of interfaceRule.unrechargeRequest
     *
     * @mbggenerated
     */
    public String getUnrechargerequest() {
        return unrechargerequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.unrechargeRequest
     *
     * @param unrechargerequest the value for interfaceRule.unrechargeRequest
     *
     * @mbggenerated
     */
    public void setUnrechargerequest(String unrechargerequest) {
        this.unrechargerequest = unrechargerequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.unrechargeResponse
     *
     * @return the value of interfaceRule.unrechargeResponse
     *
     * @mbggenerated
     */
    public String getUnrechargeresponse() {
        return unrechargeresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.unrechargeResponse
     *
     * @param unrechargeresponse the value for interfaceRule.unrechargeResponse
     *
     * @mbggenerated
     */
    public void setUnrechargeresponse(String unrechargeresponse) {
        this.unrechargeresponse = unrechargeresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.callbackRequest
     *
     * @return the value of interfaceRule.callbackRequest
     *
     * @mbggenerated
     */
    public String getCallbackrequest() {
        return callbackrequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.callbackRequest
     *
     * @param callbackrequest the value for interfaceRule.callbackRequest
     *
     * @mbggenerated
     */
    public void setCallbackrequest(String callbackrequest) {
        this.callbackrequest = callbackrequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interfaceRule.callbackResponse
     *
     * @return the value of interfaceRule.callbackResponse
     *
     * @mbggenerated
     */
    public String getCallbackresponse() {
        return callbackresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interfaceRule.callbackResponse
     *
     * @param callbackresponse the value for interfaceRule.callbackResponse
     *
     * @mbggenerated
     */
    public void setCallbackresponse(String callbackresponse) {
        this.callbackresponse = callbackresponse;
    }

    @Override
    public String toString() {
        return "InterfaceRule{" +
                "id=" + id +
                ", merchantno='" + merchantno + '\'' +
                ", rechargerequest='" + rechargerequest + '\'' +
                ", rechargeresponse='" + rechargeresponse + '\'' +
                ", queryrequest='" + queryrequest + '\'' +
                ", queryresponse='" + queryresponse + '\'' +
                ", banlancerequest='" + banlancerequest + '\'' +
                ", balanceresponse='" + balanceresponse + '\'' +
                ", unrechargerequest='" + unrechargerequest + '\'' +
                ", unrechargeresponse='" + unrechargeresponse + '\'' +
                ", callbackrequest='" + callbackrequest + '\'' +
                ", callbackresponse='" + callbackresponse + '\'' +
                '}';
    }
}